language: ruby

rvm:
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - jruby-9.1.5.0
  - ruby-head

env:
  - COVERALL=1

cache:
  - bundler

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.0.0

before_install:
  - rvm get latest
  - gem install bundler
