{{- if (not .Values.mastodon.s3.enabled) -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "mastodon.fullname" . }}-system
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.mastodon.persistence.system.accessMode }}
  {{- with .Values.mastodon.persistence.system.resources }}
  resources:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  storageClassName: {{ .Values.mastodon.persistence.system.storageClassName }}
{{- end }}
