apiVersion: v1
kind: Service
metadata:
  name: {{ include "mastodon.fullname" . }}-streaming
  labels:
    {{- include "mastodon.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.mastodon.streaming.port }}
      targetPort: streaming
      protocol: TCP
      name: streaming
  selector:
    {{- include "mastodon.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: streaming
