language: ruby
sudo: false
cache: bundler
rvm:
  - '2.4.2'
  - '2.3.5'
gemfile:
  - Gemfile
  - gemfiles/rails4.gemfile
  - gemfiles/rails5.gemfile
script: bundle exec rake
notifications:
  email: false
env:
  global:
    secure: egPPk/jMVzOoZGkk8jcf1f1N++oI4p4hqtk53T2kpHChxpmR8sP/oFlAhebvqMhM8svbQx+lWTvdxPDj9GBQGsC4ekqubV6S0MNJQS4/F41PSEU+DFUzNU1PHiDO+/0AbIheTj15UIt8IC4NVaM236HuSdMDWOjVI3ydBsgJ/GY=
