---
shared:
  experimental_features: <%= ENV.fetch('EXPERIMENTAL_FEATURES', nil) %>
  limited_federation_mode: <%= (ENV.fetch('LIMITED_FEDERATION_MODE', nil) || ENV.fetch('WHITELIST_MODE', nil)) == 'true' %>
  self_destruct_value: <%= ENV.fetch('SELF_DESTRUCT', nil) %>
  software_update_url: <%= ENV.fetch('UPDATE_CHECK_URL', 'https://api.joinmastodon.org/update-check') %>
  source:
    base_url: <%= ENV.fetch('SOURCE_BASE_URL', nil) %>
    repository: <%= ENV.fetch('GITHUB_REPOSITORY', 'mastodon/mastodon') %>
    tag: <%= ENV.fetch('SOURCE_TAG', nil) %>
  version:
    metadata: <%= ENV.fetch('MASTODON_VERSION_METADATA', nil) %>
    prerelease: <%= ENV.fetch('MASTODON_VERSION_PRERELEASE', nil) %>
test:
  experimental_features: <%= [ENV.fetch('EXPERIMENTAL_FEATURES', nil), 'testing_only'].compact.join(',') %>
