default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
dark-purple: styles/dark-purple.scss
light-purple: styles/light-purple.scss
dark-red: styles/dark-red.scss
light-red: styles/light-red.scss
dark-green: styles/dark-green.scss
light-green: styles/light-green.scss
dark-cyan: styles/dark-cyan.scss
light-cyan: styles/light-cyan.scss
dark-yellow: styles/dark-yellow.scss
light-yellow: styles/light-yellow.scss
dark-orange: styles/dark-orange.scss
light-orange: styles/light-orange.scss
dark-pink: styles/dark-pink.scss
light-pink: styles/light-pink.scss
transparent-starry-sky: styles/transparent-starry-sky.scss
transparent-forest-trace: styles/transparent-forest-trace.scss
transparent-aurora: styles/transparent-aurora.scss
witches-town: styles/witches-town.scss
sleeping-town: styles/sleeping-town.scss
forest: styles/forest.scss
# strawberry: styles/strawberry.scss
new-year: styles/new-year.scss
nga: styles/nga.scss
RaRuRe: styles/rarure.scss
##cybre-light: styles/cybre-light.scss
# sakura: styles/sakura.scss
##luxury: styles/luxury.scss
# ubuntu-light: styles/ubuntu-light.scss
##ubuntu-terminal: styles/ubuntu-terminal.scss
##bilibili-light: styles/bilibili-light.scss
# linernotes-dark: styles/linernotes-dark.scss
# swan-lake: styles/swan-lake.scss
# cybre: styles/cybre.scss
# cyberpunk-neon: styles/cyberpunk-neon.scss
# pastel-gradient: styles/pastel-gradient.scss
# purple-haze: styles/purple-haze.scss
# geodude: styles/geodude.scss
# royal-tenenbaums: styles/royal-tenenbaums.scss