default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
compact: styles/compact.scss
instance-ticker-type-0: styles/instance-ticker-type-0.scss
instance-ticker-type-1: styles/instance-ticker-type-1.scss
instance-ticker-type-beta1: styles/instance-ticker-type-beta1.scss
