default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
dark-red: styles/dark_red.scss
light-red: styles/light_red.scss
dark-green: styles/dark_green.scss
light-green: styles/light_green.scss
dark-yellow: styles/dark_yellow.scss
light-yellow: styles/light_yellow.scss
witches-town: styles/witches-town.scss
sleeping-town: styles/sleeping-town.scss