default: styles/tootcafe.scss            # via https://github.com/tootcafe/mastodon/pull/2
mastodon: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
win95: styles/win95.scss              # via https://github.com/cybrespace/mastodon
paris: styles/paris.scss              # via https://github.com/ashfurrow/mastodon/pull/1
photon_light: styles/photon_light.scss
photon_dark: styles/photon_dark.scss
