default: styles/theme_mastodon.scss
sidem_jupiter: styles/theme_sidem_jupiter.scss
sidem_dramaticstars: styles/theme_sidem_dstars.scss
sidem_altessimo: styles/theme_sidem_alte.scss
sidem_beit: styles/theme_sidem_beit.scss
sidem_w:  styles/theme_sidem_w.scss
sidem_frame: styles/theme_sidem_frame.scss
sidem_sai: styles/theme_sidem_sai.scss
sidem_highjoker: styles/theme_sidem_hijo.scss
sidem_shinsokuikkon: styles/theme_sidem_ikkon.scss
sidem_cafeparade: styles/theme_sidem_cafe.scss
sidem_mofumofuen: styles/theme_sidem_mofu.scss
sidem_sem: styles/theme_sidem_sem.scss
sidem_kogado: styles/theme_sidem_kogado.scss
sidem_flags: styles/theme_sidem_flags.scss
sidem_legenders: styles/theme_sidem_leg.scss
