default: styles/application.scss
contrast: styles/contrast.scss
mastodon-light: styles/mastodon-light.scss
black: styles/black.scss
forest: styles/forest.scss
sakura: styles/sakura.scss
test: styles/test.scss
linernotes_dark: styles/linernotes_dark.scss
pastel-gradient: styles/pastel-gradient.scss
witches-town: styles/witches-town.scss
strawberry: styles/strawberry.scss
neoncity: styles/neon-city.scss
swan-lake: styles/swan-lake.scss
cyberpunk-neon: styles/cyberpunk-neon.scss
meemu-org: styles/meemu.scss
sleeping-town: styles/sleeping-town.scss
deep-green: styles/deep-green.scss
new-year: styles/new-year.scss
geodude: styles/geodude.scss
royal-tenenbaums: styles/royal-tenenbaums.scss
nga: styles/nga.scss
ubuntu-light: styles/ubuntu-light.scss
luxury: styles/luxury.scss
purple-haze: styles/purple-haze.scss
ubuntu-terminal: styles/ubuntu-terminal.scss
cybrespace: styles/cybre.scss
win95: styles/win95.scss
bingdaily: styles/bingdaily.scss
hellowland: styles/hellowland.scss
bilibili-light: styles/bilibili-light.scss
beebear: styles/beebear.scss