language: ruby

rvm:
  - 1.8.7
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3.0
  - jruby-18mode
  - jruby-19mode
  - jruby-9.0.5.0
  - rbx-2

gemfile: ".travis/Gemfile"

sudo: false

env:
  global:
    - VERBOSE=true
    - TIMEOUT=1
  matrix:
    - conn=ruby      REDIS_BRANCH=3.0
    - conn=ruby      REDIS_BRANCH=3.2
    - conn=hiredis   REDIS_BRANCH=3.0
    - conn=hiredis   REDIS_BRANCH=3.2
    - conn=synchrony REDIS_BRANCH=3.0
    - conn=synchrony REDIS_BRANCH=3.2
    - conn=ruby      REDIS_BRANCH=unstable

branches:
  only:
    - master

matrix:
  exclude:
    # hiredis
    - rvm: jruby-18mode
      gemfile: .travis/Gemfile
      env: conn=hiredis REDIS_BRANCH=3.0
    - rvm: jruby-18mode
      gemfile: .travis/Gemfile
      env: conn=hiredis REDIS_BRANCH=3.2
    - rvm: jruby-19mode
      gemfile: .travis/Gemfile
      env: conn=hiredis REDIS_BRANCH=3.0
    - rvm: jruby-19mode
      gemfile: .travis/Gemfile
      env: conn=hiredis REDIS_BRANCH=3.2
    - rvm: jruby-9.0.5.0
      gemfile: .travis/Gemfile
      env: conn=hiredis REDIS_BRANCH=3.0
    - rvm: jruby-9.0.5.0
      gemfile: .travis/Gemfile
      env: conn=hiredis REDIS_BRANCH=3.2

    # synchrony
    - rvm: 1.8.7
      gemfile: .travis/Gemfile
      env: conn=synchrony REDIS_BRANCH=3.0
    - rvm: 1.8.7
      gemfile: .travis/Gemfile
      env: conn=synchrony REDIS_BRANCH=3.2
    - rvm: jruby-18mode
      gemfile: .travis/Gemfile
      env: conn=synchrony REDIS_BRANCH=3.0
    - rvm: jruby-18mode
      gemfile: .travis/Gemfile
      env: conn=synchrony REDIS_BRANCH=3.2
    - rvm: jruby-19mode
      gemfile: .travis/Gemfile
      env: conn=synchrony REDIS_BRANCH=3.0
    - rvm: jruby-19mode
      gemfile: .travis/Gemfile
      env: conn=synchrony REDIS_BRANCH=3.2
    - rvm: jruby-9.0.5.0
      gemfile: .travis/Gemfile
      env: conn=synchrony REDIS_BRANCH=3.0
    - rvm: jruby-9.0.5.0
      gemfile: .travis/Gemfile
      env: conn=synchrony REDIS_BRANCH=3.2
  allow_failures:
    - rvm: rbx-2

notifications:
  irc:
    - irc.freenode.net#redis-rb
  email: false
