---
en:
  admin:
    custom_emojis:
      batch_copy_error: 'An error occurred when copying some of the selected emoji: %{message}'
      batch_error: 'An error occurred: %{message}'
    domain_allows:
      export: Export
      import: Import
    domain_blocks:
      export: Export
      import: Import
    export_domain_allows:
      new:
        title: Import domain allows
      no_file: No file selected
    export_domain_blocks:
      import:
        description_html: You are about to import a list of domain blocks. Please review this list very carefully, especially if you have not authored this list yourself.
        existing_relationships_warning: Existing follow relationships
        private_comment_description_html: 'To help you track where imported blocks come from, imported blocks will be created with the following private comment: <q>%{comment}</q>'
        private_comment_template: Imported from %{source} on %{date}
        title: Import domain blocks
      new:
        title: Import domain blocks
      no_file: No file selected
    settings:
      captcha_enabled:
        desc_html: This relies on external scripts from hCaptcha, which may be a security and privacy concern. In addition, <strong>this can make the registration process significantly less accessible to some (especially disabled) people</strong>. For these reasons, please consider alternative measures such as approval-based or invite-based registration.<br>Users that have been invited through a limited-use invite will not need to solve a CAPTCHA
        title: Require new users to solve a CAPTCHA to confirm their account
      enable_keybase:
        desc_html: Allow your users to prove their identity via keybase
        title: Enable keybase integration
      flavour_and_skin:
        title: Flavour and skin
      other:
        preamble: Various glitch-soc settings not fitting in other categories.
        title: Other
      outgoing_spoilers:
        desc_html: When federating toots, add this content warning to toots that do not have one. It is useful if your server is specialized in content other servers might want to have under a Content Warning. Media will also be marked as sensitive.
        title: Content warning for outgoing toots
      hide_followers_count:
        desc_html: Do not show followers count on user profiles
        title: Hide followers count
      show_reblogs_in_public_timelines:
        desc_html: Show public boosts of public toots in local and public timelines.
        title: Show boosts in public timelines
      show_replies_in_public_timelines:
        desc_html: In addition to public self-replies (threads), show public replies in local and public timelines.
        title: Show replies in public timelines
      trending_status_cw:
        desc_html: When trending posts are enabled, allow posts with Content Warnings to be eligible. Changes to this setting are not retroactive.
        title: Allow posts with Content Warnings to trend
  auth:
    captcha_confirmation:
      hint_html: Just one more step! To confirm your account, this server requires you to solve a CAPTCHA. You can <a href="/about/more">contact the server administrator</a> if you have questions or need assistance with confirming your account.
      title: User verification
  generic:
    use_this: Use this
  settings:
    flavours: Flavours
