---
ko:
  admin:
    dashboard:
      keybase: 키베이스 연동
    settings:
      enable_keybase:
        desc_html: 사용자들이 키베이스를 통해 개인 신원을 증명할 수 있도록 허용
        title: 키베이스 연동 활성화
      outgoing_spoilers:
        desc_html: 게시물들을 연합할 때, 열람주의가 달려있지 않다면 이 열람주의를 추가합니다. 다른 서버들이 열람주의를 하길 원하는 콘텐츠들에 특화된 서버에서 유용합니다. 미디어 또한 민감함으로 설정 됩니다.
        title: 나가는 게시물에 대한 열람주의
      hide_followers_count:
        desc_html: 사용자 프로필에 팔로워 수를 표시하지 않습니다
        title: 팔로워 수 숨기기
      show_reblogs_in_public_timelines:
        desc_html: 공개글의 공개적인 부스트를 로컬과 공개 타임라인에 표시합니다.
        title: 부스트를 공개 타임라인에 표시
      show_replies_in_public_timelines:
        desc_html: 자기자신에 대한 답글(글타래)와 마찬가지로, 공개적인 답글을 로컬과 공개 타임라인에 표시합니다.
        title: 답글을 공개 타임라인에 표시
  generic:
    use_this: 사용하기
  settings:
    flavours: 풍미
