---
pt-BR:
  simple_form:
    glitch_only: glitch-soc
    hints:
      defaults:
        fields: Você pode ter até %{count} itens exibidos como uma tabela no seu perfil
        setting_default_content_type_html: Ao escrever toots, assume que estão escritos em HTML bruto, a menos que especificado de outra forma
        setting_default_content_type_markdown: Ao escrever toots, assume que ele está usando Markdown para formatação de texto, a menos que especificado seja diferente
        setting_default_content_type_plain: Ao escrever toots, assume que eles são textos simples sem formatação especial, a menos que esteja especificado de outra forma (comportamento padrão do Mastodon)
        setting_default_language: O idioma dos seus toots pode ser detectado automaticamente, mas nem sempre é preciso
        setting_hide_followers_count: Ocultar a contagem de seguidores de todos, incluindo você. Algumas aplicações podem exibir uma contagem de seguidores negativa.
        setting_skin: Reaplica o sabor Mastodon selecionado
    labels:
      defaults:
        setting_default_content_type: Formato padrão para toots
        setting_default_content_type_html: HTML
        setting_default_content_type_markdown: Markdown
        setting_default_content_type_plain: Texto sem formatação
        setting_favourite_modal: Mostrar diálogo antes de favoritar (aplica-se somente ao sabor Glitch)
        setting_hide_followers_count: Ocultar sua contagem de seguidores
        setting_skin: Tema
        setting_system_emoji_font: Usar fonte padrão do sistema para emojis (aplica-se somente ao sabor Glitch)
      notification_emails:
        trending_link: Novo link em tendência requer revisão
        trending_status: Nova postagem em tendência requer revisão
        trending_tag: Nova tag em tendência requer revisão
