---
ko:
  simple_form:
    hints:
      defaults:
        setting_default_content_type_html: 게시물을 작성할 때, 형식을 지정하지 않았다면, 생 HTML이라고 가정합니다
        setting_default_content_type_markdown: 게시물을 작성할 때, 형식을 지정하지 않았다면, 마크다운이라고 가정합니다
        setting_default_content_type_plain: 게시물을 작성할 때, 형식을 지정하지 않았다면, 일반적인 텍스트라고 가정합니다. (마스토돈의 기본 동작)
        setting_default_language: 작성하는 게시물의 언어는 자동으로 설정될 수 있습니다, 하지만 언제나 정확하지는 않습니다
        setting_skin: 선택한 마스토돈 풍미의 스킨을 바꿉니다
    labels:
      defaults:
        setting_default_content_type: 게시물의 기본 포맷
        setting_default_content_type_html: HTML
        setting_default_content_type_markdown: 마크다운
        setting_default_content_type_plain: 일반 텍스트
        setting_favourite_modal: 관심글을 지정할 때 확인 창을 띄웁니다(글리치 풍미에만 적용됨)
        setting_hide_followers_count: 내 팔로워 수 숨기기
        setting_skin: 스킨
        setting_system_emoji_font: 에모지에 시스템 기본 폰트 적용하기 (글리치 풍미에만 적용됨)
