---
uk:
  simple_form:
    glitch_only: glitch-soc
    hints:
      defaults:
        setting_default_content_type_html: При написанні дмухів, вони записуються в необробленному HTML, якщо це не вказано інакше
        setting_default_content_type_markdown: При написанні дмухів вони використовують Markdown для форматування розширеного тексту, якщо не вказано інше
        setting_default_content_type_plain: При написанні дмухів , дмух буде звичайним текстом без спеціального форматування, якщо не вказано інше (поведінка Mastodon за замовчуванням).
        setting_default_language: Мова ваших дмухів може визначатися автоматично, але не завжди точно
        setting_hide_followers_count: Приховати кількість підписників у всіх, включаючи вас. Деякі застосунки можуть відображати негативну кількість послідовників.
        setting_skin: Відновлює звичайну тему Mastodon
    labels:
      defaults:
        setting_default_content_type: Формат дмухів за замовчуванням
        setting_default_content_type_html: HTML
        setting_default_content_type_markdown: Markdown
        setting_default_content_type_plain: Звичайний текст
        setting_favourite_modal: Показувати діалогове вікно підтвердження перед додаванням до улюблених (стосується лише теми Glitch)
        setting_hide_followers_count: Приховати кількість підписників
        setting_skin: Тема оформлення
        setting_system_emoji_font: Використовувати типовий системний шрифт для емодзі (застосовується лише до теми Glitch)
      notification_emails:
        trending_link: Нове трендове посилання потребує перегляду
        trending_status: Новий трендовий допис потребує перегляду
        trending_tag: Новий новий теґ потребує перегляду
