---
es:
  simple_form:
    hints:
      defaults:
        setting_default_content_type_html: Al escribir toots, asume que estás escritos en HTML, a menos que se especifique lo contrario
        setting_default_content_type_markdown: Al escribir toots, asume que estás usando Markdown para dar formato de texto enriquecido, a menos que se especifique lo contrario
        setting_default_content_type_plain: Al escribir toots, asume que estás usando texto sin formato, a menos que se especifique lo contrario (predeterminado de Mastodon)
        setting_default_language: El idioma de tus toots se puede detectar automáticamente, pero no siempre es correcto
        setting_skin: Cambia el diseño de la edición seleccionada de Mastodon
    labels:
      defaults:
        setting_default_content_type: Formato predeterminado de tus toots
        setting_default_content_type_plain: Sin formato
        setting_favourite_modal: Mostrar diálogo de confirmación antes de marcar como favorito (sólo aplica a la edición Glich)
        setting_hide_followers_count: Ocultar tu conteo de seguidorxs
        setting_skin: Diseño
        setting_system_emoji_font: Usar la fuente predeterminada del sistema para emojis (sólo aplica a la edición Glitch)
