---
zh-CN:
  admin:
    dashboard:
      keybase: Keybase 集成
    settings:
      enable_keybase:
        desc_html: 允许你的用户使用 Keybase 证明身份
        title: 启用 Keybase 集成
      outgoing_spoilers:
        desc_html: 在联邦化嘟文的时候，将这个内容警告添加到没有内容警告的嘟文中。如果你的服务器专用于其他服务器可能希望有内容警告的内容，它会很有用。媒体也将被标记为敏感。
        title: 对外嘟文的内容警告
      hide_followers_count:
        desc_html: 不要在用户资料中显示关注者人数
        title: 隐藏关注者人数
      show_reblogs_in_public_timelines:
        desc_html: 在本地和跨站时间线中显示公开嘟文的公开转嘟。
        title: 在公共时间线中显示转嘟
      show_replies_in_public_timelines:
        desc_html: 除了公开的自我回复（线程模式），在本地和跨站时间轴中显示公开回复。
        title: 在公共时间轴中显示回复
  generic:
    use_this: 使用这个
  settings:
    flavours: 风味
