name: Share to Mastodon
on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  share:
    runs-on: ubuntu-latest
    steps:
      - name: Share to Mastodon
        uses: cbrgm/mastodon-github-action@v1
        with:
          access-token: ${{ secrets.MASTODON_ACCESS_TOKEN }}
          message: "New update in my GitHub repository! ğŸš€ Check it out: ${{ github.event.repository.html_url }}"
          visibility: "public"
          url: "https://el.elbarand.pics/" # ì—¬ê¸°ì— ë³¸ì¸ì˜ ë§ˆìŠ¤í† ëˆ ì¸ìŠ¤í„´ìŠ¤ URLì„ ì…ë ¥í•˜ì„¸ìš”
