name: Push our docker image
on:
  push:
    branches:
      - hota/**
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  push_to_hub:
    name: Push Docker image to Docker Registry
    runs-on: ubuntu-latest
    steps:
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.REGISTRY_SERVER }}/${{ secrets.REGISTRY_REPO }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.REGISTRY_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      -
        name: Checkout akane-blue/mastodon
        uses: actions/checkout@v2
        with:
          repository: akane-blue/mastodon
          path: mastodon
      -
        name: Build and push to Docker Registry
        uses: docker/build-push-action@v2
        with:
          context: mastodon
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
